// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeVBfCPRS2MyoYEn8xj9zv2l1Ad2Jim6k',
    appId: '1:629475475735:web:0fe74b2a8068d4c97df752',
    messagingSenderId: '629475475735',
    projectId: 'hyperstore-24c09',
    authDomain: 'hyperstore-24c09.firebaseapp.com',
    storageBucket: 'hyperstore-24c09.appspot.com',
    measurementId: 'G-0ZM1EPZJL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0f7tNkdyAmSy0B81Fjhvj9bN5B7SSnsM',
    appId: '1:629475475735:android:05ea55d6452d595b7df752',
    messagingSenderId: '629475475735',
    projectId: 'hyperstore-24c09',
    storageBucket: 'hyperstore-24c09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCluGPVhtWzVMIZ9826snGic-wMt0htslI',
    appId: '1:629475475735:ios:a869e9d27ab56a207df752',
    messagingSenderId: '629475475735',
    projectId: 'hyperstore-24c09',
    storageBucket: 'hyperstore-24c09.appspot.com',
    androidClientId: '629475475735-9raqi9ebseisd5ouv1lfitgg68n6mh6u.apps.googleusercontent.com',
    iosClientId: '629475475735-j3tlv35f2mvi68ec4ksgt4pu4c4sjn9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCluGPVhtWzVMIZ9826snGic-wMt0htslI',
    appId: '1:629475475735:ios:a869e9d27ab56a207df752',
    messagingSenderId: '629475475735',
    projectId: 'hyperstore-24c09',
    storageBucket: 'hyperstore-24c09.appspot.com',
    androidClientId: '629475475735-9raqi9ebseisd5ouv1lfitgg68n6mh6u.apps.googleusercontent.com',
    iosClientId: '629475475735-j3tlv35f2mvi68ec4ksgt4pu4c4sjn9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
